version: '3.9'
services:
  api-gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_SYSTEM_ADDRESS=http://auth-system-api-1:3002
      - MAPS_SYSTEM_ADDRESS=http://geoserver-service:3001
networks:
  default:
    external:
      name: neuromaps-network